# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - ls -la .
  - yarn install

stages:
  - test
  - build-source
  - build-docker-image
  - release

# Stage: test
# Run all the jobs to make sure new source code is following team's convention

type-checking:
  stage: test
  script:
    - yarn tsc

lint-source:
  stage: test
  script:
    - yarn lint

unit-test:
  stage: test
  script:
    - yarn test:cov

# Stage: build-source
# Build the bundles

build-source:latest:
  stage: build-source
  script:
    - yarn build:development
  artifacts:
    paths:
      - build/

build-source:production:
  stage: build-source
  only:
    - tags
  script:
    - yarn build:production
  artifacts:
    paths:
      - build/

# Stage: build-docker-image
# Put bundles into docker images

build-docker-image:latest:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  stage: build-docker-image
  only:
    - master
  cache: {}
  dependencies:
    - build-source:latest
  before_script:
    - docker info
    - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_TOKEN} ${DOCKER_REGISTRY}
  script:
    - docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME} .
    - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}

build-docker-image:production:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  stage: build-docker-image
  only:
    - tags
  cache: {}
  before_script:
    - docker info
    - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_TOKEN} ${DOCKER_REGISTRY}
  script:
    - docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}

# Stage: release
# Automatically bump version, update changelog and readme
# Remove `--dry-run` when v1.0.0 release

semantic-release:
  image: node:lts-stretch
  stage: release
  only:
    - master
  script:
    - yarn changelog
    - yarn semantic-release --dry-run
