export enum SipDataType {
  BANG_KE = 'ZC1',
  BUU_GUI_CON = 'ZSML',
  CHUYEN_THU = 'ZC3',
  KIEN = 'ZBIG',
  TAI = 'ZC2',
}

export enum SipDataState {
  TAO_MOi = 101,
  GAN_BANG_KE_VAO_TAI = 102,
  GAN_TAI_KIEN_VAO_CHUYEN_THU = 103,
  HOAN_THANH_CHUYEN_THU = 104,
  CHUYEN_THU_XUAT_PHAT = 105,
  CHUYEN_THU_DEN = 106,
  CHUYEN_THU_DA_QUET_NHAN = 107,
  TAI_KIEN_DA_QUET_NHAN = 108,
  BANG_KE_DA_QUET_NHAN = 109,
}
