const REACT_APP_API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT || '';
const REACT_APP_SSO_URL = process.env.REACT_APP_SSO_URL || '';
const REACT_APP_SSO_CLIENT_ID = process.env.REACT_APP_SSO_CLIENT_ID || '';
const REACT_APP_SSO_CLIENT_SECRET = process.env.REACT_APP_SSO_CLIENT_SECRET || '';

export { REACT_APP_API_ENDPOINT, REACT_APP_SSO_CLIENT_ID, REACT_APP_SSO_CLIENT_SECRET, REACT_APP_SSO_URL };
